--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.0.908
--   Created On : sábado, 07 octubre, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;




--  Create Tables 
CREATE TABLE Proceso
(
	nombreProceso VARCHAR(50),
	idProceso INTEGER NOT NULL,
	Participantes VARCHAR(50),
	Tareas INTEGER NOT NULL,
	PRIMARY KEY (idProceso),
	KEY (Tareas),
	KEY (Participantes)

) 
;


CREATE TABLE Rol
(
	idRol INTEGER NOT NULL,
	nombreRol VARCHAR(50) NOT NULL,
	PRIMARY KEY (nombreRol),
	UNIQUE UQ_Rol_idRol(idRol)

) 
;


CREATE TABLE Tareas
(
	idTarea INTEGER NOT NULL,
	tiempoInicio DOUBLE,
	NombreTarea VARCHAR(50),
	tiempoFin DOUBLE,
	PRIMARY KEY (idTarea)

) 
;


CREATE TABLE Usuario
(
	nombre VARCHAR(50),
	Password VARCHAR(50),
	nickname VARCHAR(50) NOT NULL,
	id INTEGER NOT NULL,
	email VARCHAR(100),
	rol VARCHAR(50),
	Apellido VARCHAR(50),
	PRIMARY KEY (id),
	UNIQUE UQ_Usuario_nickname(nickname),
	KEY (rol)

) 
;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE Proceso ADD CONSTRAINT FK_Proceso_Tareas 
	FOREIGN KEY (Tareas) REFERENCES Tareas (idTarea)
;

ALTER TABLE Proceso ADD CONSTRAINT FK_Proceso_Usuario 
	FOREIGN KEY (Participantes) REFERENCES Usuario (nickname)
;

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Rol 
	FOREIGN KEY (rol) REFERENCES Rol (nombreRol)
;
