--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.0.908
--   Created On : miércoles, 11 octubre, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;




--  Create Tables 
CREATE TABLE Proceso
(
	nombreProceso VARCHAR(50),
	idProceso INTEGER NOT NULL,
	Participantes VARCHAR(50),
	PRIMARY KEY (idProceso),
	KEY (Participantes)

) 
;


CREATE TABLE Rol
(
	idRol INTEGER NOT NULL,
	nombreRol VARCHAR(50) NOT NULL,
	PRIMARY KEY (nombreRol),
	UNIQUE UQ_Rol_idRol(idRol)

) 
;


CREATE TABLE Tareas
(
	idTarea INTEGER NOT NULL,
	tiempoInicio DOUBLE,
	NombreTarea VARCHAR(50),
	tiempoFin DOUBLE,
	idProceso INTEGER NOT NULL,
	ejecutor INTEGER,
	PRIMARY KEY (idTarea),
	UNIQUE UQ_Tareas_idProceso(idProceso),
	KEY (idProceso),
	KEY (ejecutor)

) 
;


CREATE TABLE Usuario
(
	nombre VARCHAR(50),
	Password VARCHAR(50),
	nickname VARCHAR(50) NOT NULL,
	id INTEGER NOT NULL,
	email VARCHAR(100),
	rol VARCHAR(50),
	Apellido VARCHAR(50),
	PRIMARY KEY (id),
	UNIQUE UQ_Usuario_nickname(nickname),
	KEY (rol)

) 
;


CREATE TABLE SolicitudProceso
(
	idSolicitud INTEGER NOT NULL,
	FechaInicio DOUBLE,
	FechaLimite DOUBLE,
	Estado BIT,
	Solicitante VARCHAR(50),
	ProcesoSolicitado INTEGER,
	PRIMARY KEY (idSolicitud),
	KEY (ProcesoSolicitado),
	KEY (Solicitante)

) 
;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE Proceso ADD CONSTRAINT FK_Proceso_Usuario 
	FOREIGN KEY (Participantes) REFERENCES Usuario (nickname)
;

ALTER TABLE Tareas ADD CONSTRAINT FK_Tareas_Proceso 
	FOREIGN KEY (idProceso) REFERENCES Proceso (idProceso)
;

ALTER TABLE Tareas ADD CONSTRAINT FK_Tareas_Usuario 
	FOREIGN KEY (ejecutor) REFERENCES Usuario (id)
;

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Rol 
	FOREIGN KEY (rol) REFERENCES Rol (nombreRol)
;

ALTER TABLE SolicitudProceso ADD CONSTRAINT FK_SolicitudProceso_Proceso 
	FOREIGN KEY (ProcesoSolicitado) REFERENCES Proceso (idProceso)
;

ALTER TABLE SolicitudProceso ADD CONSTRAINT FK_SolicitudProceso_Usuario 
	FOREIGN KEY (Solicitante) REFERENCES Usuario (nickname)
;
