--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.0.908
--   Created On : jueves, 28 septiembre, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;




--  Create Tables 
CREATE TABLE Proceso
(
	nombreProceso VARCHAR(50),
	idProceso INTEGER NOT NULL,
	Participantes VARCHAR(50),
	Tareas VARCHAR(50),
	PRIMARY KEY (idProceso),
	KEY (Participantes)

) 
;


CREATE TABLE Rol
(
	idRol INTEGER NOT NULL,
	nombreRol VARCHAR(50) NOT NULL,
	PRIMARY KEY (nombreRol),
	UNIQUE UQ_Rol_idRol(idRol)

) 
;


CREATE TABLE Tareas
(
	idTarea INTEGER NOT NULL,
	tiempoTarea DOUBLE,
	participanteT VARCHAR(50),
	PRIMARY KEY (idTarea),
	KEY (participanteT)

) 
;


CREATE TABLE Usuario
(
	nombre VARCHAR(50),
	Password VARCHAR(50),
	nickname VARCHAR(50) NOT NULL,
	id INTEGER NOT NULL,
	email VARCHAR(100),
	rol VARCHAR(50),
	PRIMARY KEY (id),
	UNIQUE UQ_Usuario_nickname(nickname)

) 
;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE Proceso ADD CONSTRAINT FK_Proceso_Usuario 
	FOREIGN KEY (Participantes) REFERENCES Usuario (nickname)
;

ALTER TABLE Tareas ADD CONSTRAINT FK_Tareas_Usuario 
	FOREIGN KEY (participanteT) REFERENCES Usuario (nickname)
;
